name: FitBot (daily)

on:
  schedule:
    - cron: "55 7 * * *"      # 09:55 Madrid (CEST=UTC+2)
    - cron: "0-30/5 8 * * *"  # 10:00..10:30 Madrid, cada 5 min
  workflow_dispatch:

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - name: Run FitBot in Docker
        run: |
          docker run --rm \
            -e email='${{ secrets.AH_EMAIL }}' \
            -e password='${{ secrets.AH_PASSWORD }}' \
            -e 'booking-goals=${{ secrets.BOOKING_GOALS_ESCAPED }}' \
            -e 'box-name=${{ secrets.BOX_NAME }}' \
            -e 'box-id=${{ secrets.BOX_ID }}' \
            -e 'days-in-advance=${{ secrets.DAYS_IN_ADVANCE }}' \
            -e 'family-id=${{ secrets.FAMILY_ID }}' \
            -e 'proxy=${{ secrets.PROXY }}' \
            pablobuenaposada/fitbot
