name: FitBot (daily)

on:
  schedule:
    # 06:05 UTC = 08:05 Europe/Madrid (en horario de verano).
    - cron: "55 7 * * *"      # 09:55 local
    - cron: "0-30/5 8 * * *"  # 10:00..10:30 local, cada 5 min
  workflow_dispatch:

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - name: Run FitBot in Docker
        env:
          AH_EMAIL: ${{ secrets.AH_EMAIL }}
          AH_PASSWORD: ${{ secrets.AH_PASSWORD }}
          BOX_NAME: ${{ secrets.BOX_NAME }}
          BOX_ID: ${{ secrets.BOX_ID }}     
          DAYS_IN_ADVANCE: ${{ secrets.DAYS_IN_ADVANCE }} 
          FAMILY_ID: ${{ secrets.FAMILY_ID }}
          PROXY: ${{ secrets.PROXY }}
          BOOKING_GOALS_JSON: ${{ secrets.BOOKING_GOALS_JSON }}
        run: |
          docker run --rm \
            -e email="$AH_EMAIL" \
            -e password="$AH_PASSWORD" \
            -e "booking-goals=$BOOKING_GOALS_JSON" \
            -e "box-name=$BOX_NAME" \
            -e "box-id=$BOX_ID" \
            -e "days-in-advance=$DAYS_IN_ADVANCE" \
            -e "family-id=$FAMILY_ID" \
            -e "proxy=$PROXY" \
            pablobuenaposada/fitbot
