name: FitBot (daily)

on:
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - name: "Sacamuelas"
            email_secret: AH_EMAIL
            password_secret: AH_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          # Add more users here:
          # - name: "User 2"
          #   email_secret: AH_EMAIL_2
          #   password_secret: AH_PASSWORD_2
          #   box_name: crossfitgerak
          #   box_id: 10287
          #   days_in_advance: 2
          #   booking_goals_raw: '{"0":{"time":"0900","name":"CrossFit"},"1":{"time":"0900","name":"CrossFit"}}'
      fail-fast: false  # Continue running other jobs even if one fails
    name: Run fitbot for ${{ matrix.user.name }}
    steps:
      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/fitbot-image.tar
          key: docker-fitbot-${{ github.run_id }}
          restore-keys: |
            docker-fitbot-
      
      - name: Load cached Docker image
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/fitbot-image.tar
      
      - name: Pull and cache Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          docker pull pablobuenaposada/fitbot
          docker save pablobuenaposada/fitbot -o /tmp/fitbot-image.tar
      
      - name: Run fitbot for ${{ matrix.user.name }}
        run: |
          docker run \
            -e email='${{ secrets[matrix.user.email_secret] }}' \
            -e password='${{ secrets[matrix.user.password_secret] }}' \
            -e booking-goals='${{ matrix.user.booking_goals_raw }}' \
            -e box-name='${{ matrix.user.box_name }}' \
            -e box-id='${{ matrix.user.box_id }}' \
            -e days-in-advance='${{ matrix.user.days_in_advance }}' \
            -e proxy='${{ secrets.PROXY }}' \
            pablobuenaposada/fitbot
