name: FitBot (daily)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate cache key
        id: cache-key
        run: echo "key=docker-fitbot-${{ hashFiles('Makefile', 'Dockerfile', 'src/**', 'pyproject.toml', 'uv.lock') }}" >> $GITHUB_OUTPUT
      
      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/fitbot-image.tar
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            docker-fitbot-
      
      - name: Build and cache Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          make docker/build
          docker save fitbot -o /tmp/fitbot-image.tar
  
  run:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - name: "Guille"
            email_secret: AH_EMAIL
            password_secret: AH_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Deeiif"
            email_secret: ROMA_EMAIL
            password_secret: ROMA_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Anton"
            email_secret: ANTON_EMAIL
            password_secret: ANTON_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Maria"
            email_secret: MARIA_EMAIL
            password_secret: MARIA_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Adrian"
            email_secret: ADRIAN_EMAIL
            password_secret: ADRIAN_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Adrian Lombas"
            email_secret: ADRIAN_LOMBAS_EMAIL
            password_secret: ADRIAN_LOMBAS_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
      fail-fast: false  # Continue running other jobs even if one fails
    name: Run fitbot for ${{ matrix.user.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Restore Docker image from cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/fitbot-image.tar
          key: ${{ needs.build.outputs.cache-key }}
          fail-on-cache-miss: true
      
      - name: Load Docker image
        run: docker load -i /tmp/fitbot-image.tar
      
      - name: Run fitbot for ${{ matrix.user.name }} (with retry)
        timeout-minutes: 10
        env:
          BOOKING_GOALS_JSON: ${{ matrix.user.booking_goals_raw }}
        run: |
          # Small initial delay to ensure we're past the exact opening time
          echo "⏳ Waiting 10 seconds to ensure booking window is open..."
          sleep 15
          
          i=1
          max_attempts=5
          
          while [ $i -le $max_attempts ]; do
            echo "=== Attempt $i/$max_attempts for ${{ matrix.user.name }} ==="
            OUTPUT=$(docker run \
              -e "email=${{ secrets[matrix.user.email_secret] }}" \
              -e "password=${{ secrets[matrix.user.password_secret] }}" \
              -e "booking-goals=$BOOKING_GOALS_JSON" \
              -e "box-name=${{ matrix.user.box_name }}" \
              -e "box-id=${{ matrix.user.box_id }}" \
              -e "days-in-advance=${{ matrix.user.days_in_advance }}" \
              -e "proxy=${{ secrets.PROXY }}" \
              fitbot 2>&1)
            
            echo "$OUTPUT"
            
            if echo "$OUTPUT" | grep -q "Class booked successfully\|Class already booked. Nothing to do"; then
              echo "✅ SUCCESS: Booking completed successfully on attempt $i"
              exit 0
            elif echo "$OUTPUT" | grep -q "There is no booking-goal for"; then
              echo "ℹ️ INFO: No booking goal configured for this day on attempt $i"
              exit 0
            elif echo "$OUTPUT" | grep -q "No class with the text\|Box is closed\|No credit available\|Too many wrong attempts\|Incorrect credentials"; then
              echo "❌ FATAL ERROR: Non-retriable error found on attempt $i"
              echo "$OUTPUT"
              exit 1
            elif echo "$OUTPUT" | grep -q "Too soon to book the class"; then
              echo "⏰ TOO SOON: Booking window not yet open on attempt $i"
              if [ $i -lt $max_attempts ]; then
                # Shorter delays since we're running at the right time: 10s, 20s, 40s, 80s
                delay=$((10 * (2 ** ($i - 1))))
                echo "⏳ Waiting $delay seconds before next attempt..."
                sleep $delay
              fi
            else
              echo "❌ UNKNOWN ERROR: Attempt $i failed with unknown error"
              if [ $i -lt $max_attempts ]; then
                # Shorter delay for unknown errors: 15s, 30s, 60s, 120s
                delay=$((15 * (2 ** ($i - 1))))
                echo "⏳ Waiting $delay seconds before next attempt..."
                sleep $delay
              fi
            fi
            
            i=$((i + 1))
          done
          
          echo "❌ FAILED: Maximum attempts ($max_attempts) reached without success"
          exit 1
