name: FitBot (daily)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate cache key
        id: cache-key
        run: echo "key=docker-fitbot-${{ hashFiles('Makefile', 'Dockerfile', 'src/**', 'pyproject.toml', 'uv.lock') }}" >> $GITHUB_OUTPUT
      
      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/fitbot-image.tar
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            docker-fitbot-
      
      - name: Build and cache Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          make docker/build
          docker save fitbot -o /tmp/fitbot-image.tar
  
  run:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - name: "Guille"
            email_secret: AH_EMAIL
            password_secret: AH_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Deeiif"
            email_secret: ROMA_EMAIL
            password_secret: ROMA_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Anton"
            email_secret: ANTON_EMAIL
            password_secret: ANTON_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Jesusin"
            email_secret: JESUSIN_EMAIL
            password_secret: JESUSIN_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Maria"
            email_secret: MARIA_EMAIL
            password_secret: MARIA_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Adrian"
            email_secret: ADRIAN_EMAIL
            password_secret: ADRIAN_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          - name: "Adrian Lombas"
            email_secret: ADRIAN_LOMBAS_EMAIL
            password_secret: ADRIAN_LOMBAS_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals_raw: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
      fail-fast: false  # Continue running other jobs even if one fails
    name: Run fitbot for ${{ matrix.user.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Restore Docker image from cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/fitbot-image.tar
          key: ${{ needs.build.outputs.cache-key }}
          fail-on-cache-miss: true
      
      - name: Load Docker image
        run: docker load -i /tmp/fitbot-image.tar
      
      - name: Run fitbot for ${{ matrix.user.name }}
        env:
          BOOKING_GOALS_JSON: ${{ matrix.user.booking_goals_raw }}
        run: |
          docker run \
            -e "email=${{ secrets[matrix.user.email_secret] }}" \
            -e "password=${{ secrets[matrix.user.password_secret] }}" \
            -e "booking-goals=$BOOKING_GOALS_JSON" \
            -e "box-name=${{ matrix.user.box_name }}" \
            -e "box-id=${{ matrix.user.box_id }}" \
            -e "days-in-advance=${{ matrix.user.days_in_advance }}" \
            -e "proxy=${{ secrets.PROXY }}" \
            fitbot
