name: FitBot (daily)

on:
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - name: "Sacamuelas"
            email_secret: AH_EMAIL
            password_secret: AH_PASSWORD
            box_name: crossfitgerak
            box_id: 10287
            days_in_advance: 2
            booking_goals: '{"0":{"time":"0800","name":"CrossFit"},"1":{"time":"0800","name":"CrossFit"},"2":{"time":"0800","name":"CrossFit"},"3":{"time":"0800","name":"CrossFit"},"4":{"time":"0800","name":"CrossFit"}}'
          # Add more users here:
          # - name: "User 2"
          #   email_secret: AH_EMAIL_2
          #   password_secret: AH_PASSWORD_2
          #   booking_goals: '{"0":{"time":"0900","name":"CrossFit"},"1":{"time":"0900","name":"CrossFit"}}'
      fail-fast: false  # Continue running other jobs even if one fails
    name: Run fitbot for ${{ matrix.user.name }}
    steps:
      - name: Run fitbot for ${{ matrix.user.name }}
        env:
          USER_EMAIL: ${{ secrets[matrix.user.email_secret] }}
          USER_PASSWORD: ${{ secrets[matrix.user.password_secret] }}
          BOOKING_GOALS: ${{ matrix.user.booking_goals }}
          BOX_NAME: ${{ matrix.user.box_name }}
          BOX_ID: ${{ matrix.user.box_id }}
          DAYS_IN_ADVANCE: ${{ matrix.user.days_in_advance }}
          PROXY: ${{ secrets.PROXY }}
        run: |
          docker run \
            -e "email=${USER_EMAIL}" \
            -e "password=${USER_PASSWORD}" \
            -e "booking-goals=${BOOKING_GOALS}" \
            -e "box-name=${BOX_NAME}" \
            -e "box-id=${BOX_ID}" \
            -e "days-in-advance=${DAYS_IN_ADVANCE}" \
            -e "proxy=${PROXY}" \
            pablobuenaposada/fitbot
